# Generated by Django 5.0.2 on 2024-02-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_br', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='color',
        ),
    ]
